// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtpskvCy7dxhXLm5vXtOpjRppxUM9lv30',
    appId: '1:482583214762:web:a85af2b3f005eead2e2ed3',
    messagingSenderId: '482583214762',
    projectId: 'krisimitra-090608',
    authDomain: 'krisimitra-090608.firebaseapp.com',
    storageBucket: 'krisimitra-090608.firebasestorage.app',
    measurementId: 'G-KNQTZZET69',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBij7IJ66bRSncpe3nyDC0Mv337LnTFvmU',
    appId: '1:482583214762:ios:8db2466fbf20d9992e2ed3',
    messagingSenderId: '482583214762',
    projectId: 'krisimitra-090608',
    storageBucket: 'krisimitra-090608.firebasestorage.app',
    iosBundleId: 'com.example.kisanmitra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtpskvCy7dxhXLm5vXtOpjRppxUM9lv30',
    appId: '1:482583214762:web:be2c2a1d930b8aa82e2ed3',
    messagingSenderId: '482583214762',
    projectId: 'krisimitra-090608',
    authDomain: 'krisimitra-090608.firebaseapp.com',
    storageBucket: 'krisimitra-090608.firebasestorage.app',
    measurementId: 'G-TXRFH15B6E',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBij7IJ66bRSncpe3nyDC0Mv337LnTFvmU',
    appId: '1:482583214762:ios:8db2466fbf20d9992e2ed3',
    messagingSenderId: '482583214762',
    projectId: 'krisimitra-090608',
    storageBucket: 'krisimitra-090608.firebasestorage.app',
    iosBundleId: 'com.example.kisanmitra',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2s43kcwa_kMtjbxHWtX7AOy-KHOuOdoE',
    appId: '1:482583214762:android:69e52cef2e615a002e2ed3',
    messagingSenderId: '482583214762',
    projectId: 'krisimitra-090608',
    storageBucket: 'krisimitra-090608.firebasestorage.app',
  );

}